spring.application.name=demo;

server.port=8081
# Database ? change campus_facility to your database
spring.datasource.url=jdbc:mysql://localhost:3306/campus_incidents
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate ? auto creates tables
pring.jpa.show-sql=true;
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# JWT secret ? must be same across all services
jwt.secret=SmartCampus2026SecretKeyForJWTTokenGeneration