import React, { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import * as bookingService from '../services/bookingService';

function BookingAdminPage() {
  const [bookings, setBookings] = useState([]);
  const [stats, setStats] = useState({ approved: 0, pending: 0, rejected: 0, cancelled: 0 });
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [bookingsData, statsData] = await Promise.all([
        bookingService.getAllBookings(),
        bookingService.getBookingStats()
      ]);
      setBookings(bookingsData);
      setStats(statsData);
    } catch (err) {
      console.error('Error fetching admin data', err);
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async (id) => {
    try {
      await bookingService.approveBooking(id);
      fetchData();
    } catch (err) {
      alert('Error approving booking. It may conflict with another approved booking.');
    }
  };

  const handleReject = async (id) => {
    const reason = window.prompt('Enter rejection reason:');
    if (reason !== null) {
      try {
        await bookingService.rejectBooking(id, reason);
        fetchData();
      } catch (err) {
        alert('Error rejecting booking');
      }
    }
  };

  const getStatusStyles = (status) => {
    switch (status) {
      case 'APPROVED': return { label: 'Approved', background: 'rgba(34,197,94,0.18)', color: '#A7F3D0' };
      case 'PENDING': return { label: 'Pending', background: 'rgba(250,204,21,0.18)', color: '#FCD34D' };
      case 'REJECTED': return { label: 'Rejected', background: 'rgba(239,68,68,0.18)', color: '#FCA5A5' };
      case 'CANCELLED': return { label: 'Cancelled', background: 'rgba(148,163,184,0.18)', color: '#CBD5E1' };
      default: return { label: status, background: 'rgba(148,163,184,0.12)', color: '#E2E8F0' };
    }
  };

  const chartData = [
    { label: 'Approved', value: stats.approved, color: '#22C55E' },
    { label: 'Pending', value: stats.pending, color: '#FBBF24' },
    { label: 'Rejected', value: stats.rejected, color: '#EF4444' },
    { label: 'Cancelled', value: stats.cancelled, color: '#64748B' }
  ];

  const totalCount = chartData.reduce((sum, item) => sum + item.value, 0) || 1;
  let chartOffset = 0;
  const radius = 84;
  const circumference = 2 * Math.PI * radius;
  const filteredBookings = bookings.filter((booking) => {
    const query = searchQuery.trim().toLowerCase();
    if (!query) return true;
    return [
      booking.userName,
      booking.userId,
      booking.resourceName,
      booking.resourceType,
      booking.status,
      booking.bookingDate,
      booking.startTime,
      booking.endTime
    ].some((field) => field?.toString().toLowerCase().includes(query));
  });

  const generatePdfReport = () => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const now = new Date();
    const formattedDate = now.toLocaleString();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const tableLeft = 22;
    const tableRight = pageWidth - 22;
    const rowHeight = 8;

    const addHeader = () => {
      doc.setFillColor('#F8FAFC');
      doc.rect(0, 0, pageWidth, 60, 'F');
      doc.setFontSize(18);
      doc.setTextColor('#0F172A');
      doc.setFont('helvetica', 'bold');
      doc.text('Smart Campus', margin, 24);
      doc.setFontSize(14);
      doc.setTextColor('#0F172A');
      doc.text('Booking Report', margin, 36);
      doc.setFontSize(9);
      doc.setTextColor('#475569');
      doc.text('A complete summary of booking request activity and status breakdown.', margin, 46);
      doc.setDrawColor('#CBD5E1');
      doc.setLineWidth(1);
      doc.line(margin, 56, pageWidth - margin, 56);
    };

    const addFooter = (pageNumber) => {
      doc.setDrawColor('#CBD5E1');
      doc.setLineWidth(0.4);
      doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);
      doc.setFontSize(8);
      doc.setTextColor('#0F172A');
      doc.text('Generated by Smart Campus Admin Portal', margin, pageHeight - 10);
      doc.text(`Page ${pageNumber}`, pageWidth - margin - 10, pageHeight - 10, { align: 'right' });
    };

    const addReportDetails = () => {
      const detailX = margin;
      const detailY = 68;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor('#0F172A');
      doc.text('Report Details', detailX, detailY);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor('#0F172A');
      doc.text(`Generated on: ${formattedDate}`, detailX, detailY + 8);
      doc.text('Prepared for: Campus Admin', detailX, detailY + 16);
      doc.text(`Total requests: ${bookings.length}`, detailX, detailY + 24);
      doc.text(`Filtered entries: ${filteredBookings.length}`, detailX, detailY + 32);

      const summaryBoxX = pageWidth / 2 + 10;
      const summaryBoxY = detailY - 6;
      const summaryBoxWidth = pageWidth / 2 - margin - 10;
      const summaryBoxHeight = 44;
      doc.setDrawColor('#94A3B8');
      doc.setLineWidth(0.6);
      doc.roundedRect(summaryBoxX, summaryBoxY, summaryBoxWidth, summaryBoxHeight, 6, 6, 'S');
      chartData.forEach((item, index) => {
        const y = summaryBoxY + 12 + index * 10;
        doc.setFillColor(item.color);
        doc.circle(summaryBoxX + 6, y - 2, 3, 'F');
        doc.setFontSize(9);
        doc.setTextColor('#0F172A');
        doc.text(`${item.label}: ${item.value}`, summaryBoxX + 14, y);
      });
    };

    const drawTableHeader = (y) => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor('#0F172A');
      doc.setFillColor('#E2E8F0');
      doc.rect(tableLeft - 4, y - 6, tableRight - tableLeft + 10, 10, 'F');
      const headers = ['ID', 'Requester', 'Facility', 'Schedule', 'Status'];
      const xPositions = [tableLeft, tableLeft + 20, tableLeft + 80, tableLeft + 150, tableLeft + 230];
      headers.forEach((header, idx) => {
        doc.text(header, xPositions[idx], y);
      });
    };

    addHeader();
    addReportDetails();

    let y = 110;
    drawTableHeader(y);
    y += 12;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor('#E2E8F0');

    filteredBookings.forEach((booking) => {
      if (y > pageHeight - 30) {
        addFooter(doc.internal.getNumberOfPages());
        doc.addPage();
        addHeader();
        addReportDetails();
        y = 110;
        drawTableHeader(y);
        y += 12;
      }

      if ((y - 110) / rowHeight % 2 === 0) {
        doc.setFillColor('#F3F4F6');
        doc.rect(tableLeft - 4, y - 6, tableRight - tableLeft + 10, rowHeight, 'F');
      }

      doc.setTextColor('#0F172A');
      doc.text(`#${booking.id}`, tableLeft, y);
      doc.text(booking.userName, tableLeft + 20, y);
      doc.text(booking.resourceName, tableLeft + 80, y);
      doc.text(`${booking.bookingDate} ${booking.startTime}-${booking.endTime}`, tableLeft + 150, y);
      doc.text(booking.status, tableLeft + 230, y);
      y += rowHeight;
    });

    addFooter(doc.internal.getNumberOfPages());
    doc.save('booking-report.pdf');
  };

  if (loading) {
    return (
      <div style={styles.page}>
        <div style={styles.headerCard}>
          <div style={styles.loadingText}>Loading bookings...</div>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.page}>
      <div style={styles.headerCard}>
        <div>
          <div style={styles.sectionLabel}>Booking Requests</div>
          <h2 style={styles.title}>Booking Requests Management</h2>
          <p style={styles.subtitle}>Review and manage facility booking requests across the campus in a secure admin dashboard.</p>
        </div>
        <div style={styles.headerMeta}>
          <div style={styles.metaBadge}>Admin view</div>
          <div style={styles.metaText}>Connected to booking-service on port 8084</div>
        </div>
      </div>

      <div style={styles.toolbarRow}>
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search by requester, facility, date, or status"
          style={styles.searchInput}
        />
        <button type="button" onClick={generatePdfReport} style={styles.pdfButton}>
          Download PDF Report
        </button>
      </div>

      <div style={styles.statsGrid}>
        {[
          { label: 'Pending Requests', value: stats.pending, accent: '#FBBF24' },
          { label: 'Approved', value: stats.approved, accent: '#22C55E' },
          { label: 'Rejected', value: stats.rejected, accent: '#EF4444' },
          { label: 'Cancelled', value: stats.cancelled, accent: '#64748B' }
        ].map(({ label, value, accent }) => (
          <div key={label} style={{ ...styles.statCard, borderTop: `3px solid ${accent}` }}>
            <div style={styles.statLabel}>{label}</div>
            <div style={styles.statValue}>{value}</div>
          </div>
        ))}
      </div>

      <div style={styles.tableShell}>
        <div style={styles.tableHeader}>
          <div>
            <div style={styles.tableTitle}>Pending Booking Requests</div>
            <div style={styles.tableSubtitle}>Approve or reject new campus reservations with confidence.</div>
          </div>
          <div style={styles.actionPill}>Total {filteredBookings.length} / {bookings.length}</div>
        </div>

        <div style={styles.tableWrapper}>
          <table style={styles.table}>
            <thead>
              <tr>
                {['ID', 'Requester', 'Facility', 'Schedule', 'Status', 'Actions'].map((heading) => (
                  <th key={heading} style={styles.th}>{heading}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filteredBookings.length === 0 ? (
                <tr>
                  <td colSpan="6" style={styles.emptyRow}>No bookings found.</td>
                </tr>
              ) : filteredBookings.map((booking) => {
                const statusStyle = getStatusStyles(booking.status);
                return (
                  <tr key={booking.id} style={styles.tr}>
                    <td style={styles.tdId}>#{booking.id}</td>
                    <td style={styles.tdUser}>
                      <div style={styles.primaryText}>{booking.userName}</div>
                      <div style={styles.secondaryText}>{booking.userId}</div>
                    </td>
                    <td style={styles.tdFacility}>
                      <div style={styles.primaryText}>{booking.resourceName}</div>
                      <div style={styles.secondaryText}>{booking.resourceType}</div>
                    </td>
                    <td style={styles.tdSchedule}>
                      <div style={styles.primaryText}>{booking.bookingDate}</div>
                      <div style={styles.secondaryText}>{booking.startTime} - {booking.endTime}</div>
                    </td>
                    <td style={styles.tdStatus}>
                      <span style={{ ...styles.statusPill, background: statusStyle.background, color: statusStyle.color }}>
                        {statusStyle.label}
                      </span>
                    </td>
                    <td style={styles.tdActions}>
                      {booking.status === 'PENDING' ? (
                        <div style={styles.actionGroup}>
                          <button onClick={() => handleApprove(booking.id)} style={styles.approveButton}>
                            <span style={styles.buttonIcon}>✔</span> Approve
                          </button>
                          <button onClick={() => handleReject(booking.id)} style={styles.rejectButton}>
                            <span style={styles.buttonIcon}>✖</span> Reject
                          </button>
                        </div>
                      ) : (
                        <span style={styles.noAction}>No action needed</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div style={styles.chartCard}>
        <div style={styles.chartHeader}>
          <div>
            <div style={styles.chartLabel}>Booking Status Breakdown</div>
            <div style={styles.chartTitle}>Current request distribution</div>
          </div>
        </div>
        <div style={styles.chartBody}>
          <div style={styles.pieContainer}>
            <svg viewBox="0 0 220 220" style={styles.pieChart}>
              {chartData.map((item) => {
                const length = (item.value / totalCount) * circumference;
                const strokeDasharray = `${length} ${circumference - length}`;
                const offset = -chartOffset;
                chartOffset += length;
                return (
                  <circle
                    key={item.label}
                    cx="110"
                    cy="110"
                    r={radius}
                    fill="none"
                    stroke={item.color}
                    strokeWidth="24"
                    strokeDasharray={strokeDasharray}
                    strokeDashoffset={offset}
                    style={{ transition: 'stroke-dashoffset 0.3s ease, stroke-dasharray 0.3s ease' }}
                  />
                );
              })}
              <circle cx="110" cy="110" r="60" fill="rgba(15,23,42,0.9)" />
              <text x="110" y="108" textAnchor="middle" style={styles.pieCenterValue}> {totalCount} </text>
              <text x="110" y="124" textAnchor="middle" style={styles.pieCenterLabel}> Total </text>
            </svg>
          </div>
          <div style={styles.legendGrid}>
            {chartData.map((item) => (
              <div key={item.label} style={styles.legendItem}>
                <span style={{ ...styles.legendDot, background: item.color }} />
                <div>
                  <div style={styles.legendLabel}>{item.label}</div>
                  <div style={styles.legendValue}>{item.value}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: '100vh',
    padding: '30px 24px',
    background: 'linear-gradient(135deg, #0f172a 0%, #111827 45%, #020617 100%)',
    color: '#F8FAFC'
  },
  headerCard: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 24,
    alignItems: 'flex-start',
    padding: 28,
    marginBottom: 28,
    borderRadius: 24,
    background: 'rgba(15,23,42,0.72)',
    border: '1px solid rgba(255,255,255,0.10)',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.25)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)'
  },
  sectionLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    marginBottom: 10
  },
  title: {
    fontSize: 32,
    fontWeight: 800,
    margin: 0,
    color: '#FFFFFF'
  },
  subtitle: {
    marginTop: 10,
    color: '#CBD5E1',
    fontSize: 15,
    lineHeight: 1.7,
    maxWidth: 620
  },
  headerMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minWidth: 160,
    alignItems: 'flex-end'
  },
  metaBadge: {
    color: '#FFFFFF',
    background: 'rgba(255,255,255,0.08)',
    padding: '8px 14px',
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.10)',
    fontSize: 12,
    fontWeight: 700
  },
  metaText: {
    color: '#94A3B8',
    fontSize: 13,
    textAlign: 'right'
  },
  toolbarRow: {
    display: 'flex',
    gap: 14,
    alignItems: 'center',
    marginBottom: 22,
    flexWrap: 'wrap'
  },
  searchInput: {
    flex: 1,
    minWidth: 280,
    padding: '14px 18px',
    borderRadius: 16,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.05)',
    color: '#F8FAFC',
    outline: 'none',
    fontSize: 14
  },
  pdfButton: {
    borderRadius: 16,
    background: 'linear-gradient(135deg, rgba(56,189,248,0.95), rgba(139,92,246,0.95))',
    color: '#FFFFFF',
    fontWeight: 700,
    padding: '14px 22px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 14px 32px rgba(56,189,248,0.18)'
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 16,
    marginBottom: 26
  },
  statCard: {
    borderRadius: 20,
    padding: 22,
    minHeight: 128,
    background: 'rgba(15,23,42,0.70)',
    border: '1px solid rgba(255,255,255,0.08)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)'
  },
  statLabel: {
    color: '#94A3B8',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    marginBottom: 14
  },
  statValue: {
    fontSize: 32,
    fontWeight: 800,
    color: '#FFFFFF'
  },
  tableShell: {
    borderRadius: 24,
    overflow: 'hidden',
    background: 'rgba(15,23,42,0.70)',
    border: '1px solid rgba(255,255,255,0.10)',
    backdropFilter: 'blur(18px)',
    WebkitBackdropFilter: 'blur(18px)',
    boxShadow: '0 24px 70px rgba(0, 0, 0, 0.28)'
  },
  tableHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '22px 26px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tableTitle: {
    fontSize: 22,
    fontWeight: 800,
    margin: 0,
    color: '#FFFFFF'
  },
  tableSubtitle: {
    marginTop: 6,
    color: '#94A3B8',
    fontSize: 14
  },
  actionPill: {
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(148,163,184,0.16)',
    color: '#E2E8F0',
    fontWeight: 700,
    fontSize: 13
  },
  tableWrapper: {
    overflowX: 'auto'
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    minWidth: 920
  },
  th: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: 700,
    textAlign: 'left',
    padding: '18px 18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    letterSpacing: '0.05em'
  },
  tr: {
    transition: 'background 0.2s ease'
  },
  tdId: {
    padding: '18px',
    color: '#7DD3FC',
    fontWeight: 700,
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tdUser: {
    padding: '18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tdFacility: {
    padding: '18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tdSchedule: {
    padding: '18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tdStatus: {
    padding: '18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  tdActions: {
    padding: '18px',
    borderBottom: '1px solid rgba(255,255,255,0.08)'
  },
  primaryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 600
  },
  secondaryText: {
    color: '#94A3B8',
    fontSize: 12,
    marginTop: 4
  },
  statusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '7px 14px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    minWidth: 100,
    textTransform: 'uppercase',
    letterSpacing: '0.03em'
  },
  actionGroup: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap'
  },
  approveButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    border: '1px solid rgba(34,197,94,0.35)',
    background: 'rgba(34,197,94,0.12)',
    color: '#A7F3D0',
    padding: '10px 16px',
    borderRadius: 14,
    fontWeight: 700,
    fontSize: 12,
    cursor: 'pointer'
  },
  rejectButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    border: '1px solid rgba(239,68,68,0.35)',
    background: 'rgba(239,68,68,0.12)',
    color: '#FECACA',
    padding: '10px 16px',
    borderRadius: 14,
    fontWeight: 700,
    fontSize: 12,
    cursor: 'pointer'
  },
  buttonIcon: {
    fontSize: 14,
    lineHeight: 1
  },
  noAction: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: 600
  },
  emptyRow: {
    padding: 28,
    textAlign: 'center',
    color: '#94A3B8',
    fontSize: 14
  },
  loadingText: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: 600
  },
  chartCard: {
    marginTop: 28,
    padding: 24,
    borderRadius: 24,
    background: 'rgba(15,23,42,0.70)',
    border: '1px solid rgba(255,255,255,0.10)',
    backdropFilter: 'blur(18px)',
    WebkitBackdropFilter: 'blur(18px)'
  },
  chartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 22
  },
  chartLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    marginBottom: 6
  },
  chartTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 800
  },
  chartBody: {
    display: 'flex',
    gap: 28,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap'
  },
  pieContainer: {
    width: 240,
    minWidth: 240,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center'
  },
  pieChart: {
    width: '100%',
    height: 'auto',
    transform: 'rotate(-90deg)'
  },
  pieCenterValue: {
    fontSize: '20px',
    fontWeight: 800,
    fill: '#F8FAFC'
  },
  pieCenterLabel: {
    fontSize: '11px',
    fill: '#94A3B8'
  },
  legendGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 16,
    flex: 1
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: 14,
    borderRadius: 18,
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)'
  },
  legendDot: {
    width: 14,
    height: 14,
    borderRadius: '50%'
  },
  legendLabel: {
    color: '#FFFFFF',
    fontWeight: 700,
    fontSize: 13
  },
  legendValue: {
    color: '#94A3B8',
    fontSize: 12,
    marginTop: 4
  }
};

export default BookingAdminPage;
